[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `mongo-reactive` feature to configure the native MongoDB driver in your project:
----
$ mn create-app my-app --features mongo-reactive
----
====

Micronaut includes a configuration to automatically configure the native MongoDB Java driver. To use this configuration, add the following dependency to your application:

dependency:micronaut-mongo-reactive[groupId="io.micronaut.configuration"]

Then configure the URI of the MongoDB server in `application.yml`:

.Configuring a MongoDB server
[source,yaml]
----
mongodb:
    uri: mongodb://username:password@localhost:27017/databaseName
----

TIP: The `mongodb.uri` follows the https://docs.mongodb.com/manual/reference/connection-string[MongoDB Connection String] format.

A non-blocking Reactive Streams http://mongodb.github.io/mongo-java-driver-reactivestreams/1.8/javadoc/com/mongodb/reactivestreams/client/MongoClient.html[MongoClient] is then available for dependency injection.

To use the blocking driver, add a dependency to your application to the `micronaut-mongo-sync` module.

dependency:micronaut-mongo-sync[groupId="io.micronaut.configuration"]

Then the blocking https://mongodb.github.io/mongo-java-driver/4.0/apidocs/com/mongodb/client/MongoClient.html[MongoClient] will be available for injection.


==== Using GORM for MongoDB

[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `mongo-gorm` feature to configure GORM for MongoDB in your project:
----
$ mn create-app my-app --features mongo-gorm
----
====

For Groovy users and users familiar with Grails, special support has been added to Micronaut for using http://gorm.grails.org/latest/mongodb/manual[GORM for MongoDB].

To add support for GORM for MongoDB, first configure the MongoDB connection as per instructions earlier in the guide, then add the following dependency to your application:

.build.gradle
[source,groovy]
----
compile "io.micronaut.configuration:micronaut-mongo-gorm"
----

WARNING: For GORM for MongoDB you will need to configure the database name separately as the `grails.mongodb.databaseName` property in `application.yml`.

The following should be noted regarding using GORM for MongoDB in Micronaut:

* Each class you wish to be a GORM entity should be annotated with the `grails.gorm.annotation.Entity` annotation.
* Each method that interacts with GORM should be annotated with GORM's `grails.gorm.transactions.Transactional` to ensure a session is present. You can also add the `@Transactional` annotation to the class.
* By default Micronaut will scan for entities relative to your `Application` class. If you wish to customize this specify additional packages via the api:context.ApplicationContextBuilder[] when starting your application.
