[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `mongo-reactive` feature to configure the native MongoDB driver in your project:
----
$ mn create-app my-app --features mongo-reactive
----
====

Micronaut includes a configuration to automatically configure the native MongoDB Java driver. To use this configuration, add the following dependency to your application:

dependency:micronaut-mongo-reactive[groupId="io.micronaut.mongodb"]

Then configure the URI of the MongoDB server in `application.yml`:

.Configuring a MongoDB server
[source,yaml]
----
mongodb:
    uri: mongodb://username:password@localhost:27017/databaseName
----

TIP: The `mongodb.uri` follows the https://docs.mongodb.com/manual/reference/connection-string[MongoDB Connection String] format.

A non-blocking Reactive Streams http://mongodb.github.io/mongo-java-driver-reactivestreams/1.8/javadoc/com/mongodb/reactivestreams/client/MongoClient.html[MongoClient] is then available for dependency injection.

To use the blocking driver, add a dependency to your application to the `micronaut-mongo-sync` module.

dependency:micronaut-mongo-sync[groupId="io.micronaut.mongodb"]

Then the blocking https://mongodb.github.io/mongo-java-driver/4.0/apidocs/com/mongodb/client/MongoClient.html[MongoClient] will be available for injection.
