[versions]
micronaut = "4.0.0-SNAPSHOT"
micronaut-docs = "2.0.0"
micronaut-gradle-plugin = "3.6.3"

groovy = "4.0.6"

managed-mongo = "4.7.1"
managed-mongo-reactive = "4.7.1"
flapdoodle = "2.2.0"

[libraries]
managed-mongo-core = { module = "org.mongodb:mongodb-driver-core", version.ref = "managed-mongo" }
managed-mongo-driver = { module = "org.mongodb:mongodb-driver-sync", version.ref = "managed-mongo" }
managed-mongo-reactive = { module = "org.mongodb:mongodb-driver-reactivestreams", version.ref = "managed-mongo-reactive" }

testcontainers-spock = { module = "org.testcontainers:spock" }

reactor = { module = 'io.projectreactor:reactor-core' }

flapdoodle = { module = 'de.flapdoodle.embed:de.flapdoodle.embed.mongo', version.ref = 'flapdoodle'}

# PLUGINS

gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
