[versions]
micronaut = "4.1.2"
micronaut-platform = "4.0.3"
micronaut-docs = "2.0.0"
micronaut-gradle-plugin = "4.0.3"

groovy = "4.0.13"
spock = "2.3-groovy-4.0"
testcontainers = "1.19.0"

managed-mongo = "4.10.2"
managed-mongo-reactive = "4.10.2"

micronaut-micrometer = "5.0.1"
micronaut-serde = "2.2.1"
micronaut-test = "4.0.1"
micronaut-testresources = "2.0.0"
micronaut-validation = "4.0.1"
micronaut-logging = "1.0.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

managed-mongo-core = { module = "org.mongodb:mongodb-driver-core", version.ref = "managed-mongo" }
managed-mongo-driver = { module = "org.mongodb:mongodb-driver-sync", version.ref = "managed-mongo" }
managed-mongo-reactive = { module = "org.mongodb:mongodb-driver-reactivestreams", version.ref = "managed-mongo-reactive" }

micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-test = { module = "io.micronaut.test:micronaut-test-bom", version.ref = "micronaut-test" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
micronaut-logging = { module = "io.micronaut.logging:micronaut-logging-bom", version.ref = "micronaut-logging" }

testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }

# PLUGINS
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
