[versions]
micronaut = "5.0.0-M13"
micronaut-test = "5.0.0-M3"
micronaut-platform = "4.10.5"
micronaut-gradle-plugin = "4.6.2"

managed-mongo = "5.6.4"
managed-mongo-reactive = "5.6.4"

micronaut-micrometer = "5.13.2"
micronaut-serde = "3.0.0-M2"
micronaut-validation = "5.0.0-M1"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

managed-mongo-core = { module = "org.mongodb:mongodb-driver-core", version.ref = "managed-mongo" }
managed-mongo-driver = { module = "org.mongodb:mongodb-driver-sync", version.ref = "managed-mongo" }
managed-mongo-reactive = { module = "org.mongodb:mongodb-driver-reactivestreams", version.ref = "managed-mongo-reactive" }

micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
testcontainers = { module = "org.testcontainers:testcontainers" }
testcontainers-mongodb = { module = "org.testcontainers:testcontainers-mongodb" }

# PLUGINS
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
