[versions]
micronaut = "3.5.0"
micronaut-docs = "2.0.0"
groovy = "3.0.9"

managed-mongo = "4.6.0"
managed-mongo-reactive = "4.6.0"
flapdoodle = "2.2.0"

[libraries]
managed-mongo-core = { module = "org.mongodb:mongodb-driver-core", version.ref = "managed-mongo" }
managed-mongo-driver = { module = "org.mongodb:mongodb-driver-sync", version.ref = "managed-mongo" }
managed-mongo-reactive = { module = "org.mongodb:mongodb-driver-reactivestreams", version.ref = "managed-mongo-reactive" }

testcontainers-spock = { module = "org.testcontainers:spock" }

reactor = { module = 'io.projectreactor:reactor-core' }

flapdoodle = { module = 'de.flapdoodle.embed:de.flapdoodle.embed.mongo', version.ref = 'flapdoodle'}
