plugins {
    id 'io.micronaut.build.internal.mongodb-docs-example'
}

dependencies {
    testAnnotationProcessor platform(mn.micronaut.core.bom)
    testAnnotationProcessor mn.micronaut.inject.java

    testImplementation mnTest.micronaut.test.junit5
    testRuntimeOnly mnTest.junit.jupiter.engine
}
